# (C) Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Build and check tools
---
name: tools CI
on:
  pull_request:
  workflow_call:
    inputs:
      release:
        default: 'false'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coco-play:
    runs-on: ubuntu-24.04
    env:
        GO_VERSION: '1.22'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Golang version ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/go.sum"

      - name: Build
        run: |
          COMMIT_SHORT="$(git rev-parse --short HEAD)"
          echo "COMMIT_SHORT=${COMMIT_SHORT}" >> $GITHUB_ENV
          LDFLAGS="-X 'github.com/wainersm/coco-play/pkg/versions.GitCommit=${COMMIT_SHORT}'"
          go build -ldflags="$LDFLAGS" .

      - name: Check version
        run: |
          ./coco-play version | grep -e "coco-play version: .*-${COMMIT_SHORT}"

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.4'

      - name: test
        run: |
          go test -v -count=1 ./test/e2e/

      # Gonna upload the binary to later publish in a release
      - name: Upload the executable
        if: inputs.release == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coco-play-executable
          path: ./coco-play